name: gateway-stag

services:
  gateway:
    build: .
    container_name: gateway-stag
    ports:
      - "4001:4001"
    env_file: .env.staging
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: gateway-mongo-stag
    ports:
      - "27019:27017"
    volumes:
      - gateway_mongo_stag_data:/data/db
    restart: unless-stopped

volumes:
  gateway_mongo_stag_data:
