pipeline:
  maas:
    enabled: false
  ocr_api:
    api_host: ollama
    api_port: 11434
    api_path: /api/generate
    model: glm-ocr:latest
    api_mode: ollama_generate
  layout:
    use_polygon: false
